scrapy:
  initUrl: 'http://www.mktgroup.ae/'
  category: 'mktgroup'
  pageSize: 128
  beginPage: 1
  scrolling: 1
  scrollingTimes: 5
  scrollingOffset: 100
  scrollingDuration: 1
  pageSchema: '&page='
  loadingCookie: 0
  cookieDirectory: '/Users/gilbert/instagram/'
  userName: 'wanghan52@126.com'
  loadingCookieUrl: 'https://www.instagram.com/'
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync