scrapy:
  initUrl: 'http://www.shannylighting.com/'
  category: 'shannylighting'
  pageSize: 16
  beginPage: 1
  scrolling: 0
  scrollingTimes: 50
  scrollingOffset: 2500
  scrollingDuration: 5
  pageSchema: '?page='
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync