scrapy:
  initUrl: 'https://www.dolphinstationery.com/en/categories/school-products/playing-doughs/73/playing-doughs.html'
  category: 'dolphinstationery'
  pageSize: 100
  beginPage: 1
  scrolling: 0
  scrollingTimes: 50
  scrollingOffset: 2500
  scrollingDuration: 5
  pageSchema: '?page='
  loadingCookie: 0
  cookieDirectory: '/Users/gilbert/instagram/'
  userName: 'wanghan52@126.com'
  loadingCookieUrl: 'https://www.instagram.com/'
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync