scrapy:
  initUrl: 'https://oveisgharan.ae/'
  category: 'oveisgharan'
  pageSize: 16
  beginPage: 1
  pageSchema: 'page/'
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync