scrapy:
  initUrl: 'https://stargoldworld.com/shop/'
  category: 'stargoldworld'
  pageSize: 12
  beginPage: 1
  scrolling: 0
  pageSchema: 'page/'
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync