fakhruddinsouq:
  userName: 'wanghan52@126.com'
  cookieDir: '/Users/gilbert/fakhruddinsouq/'
  initUrl: 'https://www.fakhruddinsouq.com/hardware-tools'
  category: 'hardware-tools'
  totalPages: 2
  begin: 1
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync
