farookonline:
  initUrl: 'https://www.farookonline.com/category/office-school-products'
  category: 'farookonline'
  clicks: 100
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync