farookonline:
  initUrl: 'https://www.farookonline.com/category/dairy-2024'
  category: 'farookonline'
  clicks: 20
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync