saifalfares:
  userName: 'wanghan52@126.com'
  cookieDir: '/Users/gilbert/saifalfares/'
  initUrl: 'https://saifalfares.com/collections/perfume'
  category: 'perfume'
  totalPages: 1
  begin: 1
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync