victorwatch:
  initUrl: 'https://victorwatch.com/collections/all'
  category: 'victorwatch'
  totalPages: 13
  begin: 1
  db:
    host: 192.168.8.12
    port: 13306
    user: root
    pass: KPqazxsw
    dbName: kp_sk_sync